### PR TITLE
Add interactive visualizations

### PR DESCRIPTION
**Pull request by hdoupe**
This PR adds interactive visualizations like Dash and Bokeh apps.

My _tentative_ plan is to let modelers add "Visualizations" to existing C/S models. Each visualization will provide:
- The tech (Bokeh, Dash, RShiny, etc)
- Name of a function to call in `functions.py` to start the server like `my_dash_app`:
```python
# functions.py
import os
from myapp import app

def get_version():
    return "test"

# ...

def my_dash_app():
    app.run_server(port=os.environ["PORT"])
```

C/S will then be able to install it like any other app, have a function to call to spin up the server, and be able to specify which port it is listening on.

My general approach is to start from the backend and work forward to the frontend and user experience:

- [x] 1. Define way for models to expose servers (e.g. a server function name).
- [x] 2. Install and deploy model with a server function using the existing build set up.
- [x] 3. Expose server to traffic on primary webapp.
- [ ] 4. Add UI for publishing/updating visualizations. (@MattHJensen if you have some thoughts on this step, that would be helpful.)
  - [x] a. Add REST API for creating Visualizations.
  - [x] b. Update publishing app for Visualizations.
  - [ ] c. Streamline/organize/polish publish app for models and visualizations.
- [x] 5. Add C/S authentication and usage logging (in order to come up with some measure of resource pricing) to traffic.

### CODE REVIEW

**Comment by MattHJensen** [comment]
@hdoupe, will there be a streamlined process for visualizations that don't require a sever, or are you thinking about that as a separate type of content?

**Comment by hdoupe** [comment]
@MattHJensen I'm thinking that this could be on the same publish page. Something like:

_Title_: ...
_README_: ...
_Select type_: Static or Dynamic (or maybe server)
_Viz Software_: Bokeh/Plotly/etc

If static, link to a JSON file or upload file.

If dynamic, link to a GitHub repo with a `cs-config` directory, and provide a server function name.

**Comment by hdoupe** [comment]
This https://github.com/compute-tooling/compute-studio/pull/308/commits/5f082906410c21f77638e026862133555d40b86b adds HTTPS to the visualization endpoint. This is necessary for security and so that it can be [embedded on HTTPS pages](https://stackoverflow.com/questions/18327314/how-to-allow-http-content-within-an-iframe-on-a-https-site). [Traefik](https://docs.traefik.io/) is used for routing and to communicate with cloudflare and letsencrypt to automatically generate TLS certificates. 

Steps for setting up Traefik:

1. Check [`compute-studio/workers/traefik.yaml`](https://github.com/compute-tooling/compute-studio/blob/add-viz/workers/traefik.yaml) to make sure the DNS email and auth variables are configured correctly.

1. [Install Helm (version 3).](https://helm.sh/docs/intro/install/#from-script)
1. Add the Traefik helm repository and get updates:
    ```
    helm repo add traefik https://containous.github.io/traefik-helm-chart
    helm repo update
    ```
1. Install Traefik in cluster:
    ```
    helm install traefik traefik/traefik --values traefik.yaml
    ```
1. Create an `IngressRoute` for each service that we want to route to.

**Comment by hdoupe** [comment]
The most recent batch of commits adds:
- Two new tables:
  - `RunningDeployment`: This is used to manage and track visualization deployments. When a user visits a viz or embed page, a deployment and its Kubernetes resources are created. Once the Kubernetes resources are ready, the status is updated to "running", and the iframe is embedded in the webpage. Right now, I'm using a JavaScript snippet to query the C/S API for the deployment status.
  - `EmbedApproval`: This is used to track information about how a viz can be embedded on another website. Users will be able to set up an embed approval by filling out a form with a name for the viz and a url for the site that it will be embedded on. Right now, I'm just setting these up manually. When the embed version of the viz page is loaded, the [`frame-ancestors`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors) CSP is set to the registered domain. This only allows the viz to be embedded on the registered site.

- API for managing visualization server deployments in the Kubernetes cluster. It has these endpoints:
  - `POST -- deployments/:owner/:title/` : creates a new deployment.
  - `GET -- deployments/:owner/:title/:deployment_name/`: check status of deployment
  - `DELETE -- deployments/:owner/:title/:deployment_name/`: delete deployment

Next up, I'm going to add:
- [ ] A Kubernetes `CronJob` to check the `last_loaded_at` field for active deployments so that the stale ones can be shutdown.
- [ ] Password system for the workers API.
- [ ] Circle back to @MattHJensen's UI feedback.

**Comment by hdoupe** [comment]
Latest commits add:
- List/Delete API methods that are only available internally that are used to get all active deployments and delete them if necessary.
- Ping API method that is hit by a javascript snippet that is in the visualization and embed pages. Every 10 seconds or so it hits the API to let the server know that the viz is still active. The [`document.hasFocus()`](https://developer.mozilla.org/en-US/docs/Web/API/Document/hasFocus) browser method used to determine if the user is on the page with the visualization or not. For example, if you swap to a different tab or application, the script will stop sending pings and the server will be shut off after the set period of time.
- New command in `csw` for getting running deployments from the C/S API and deleting ones that haven't been loaded or pinged in half an hour or more. I chose 30 minutes somewhat arbitrarily, and could be any length of time. We will probably have to tweak this some to figure out what works best:
Screenshot from 2020-08-25 16-43-13
- A new `CronJob` that runs the `csw models rm-stale-deployments` command every 15 minutes.

**Comment by hdoupe** [comment]
Latest commits set up an authentication system between the kubernetes cluster and the webapp. This ensures that the kubernetes cluster can verify that the webapp is sending requests to it which is much more important now that the kubernetes cluster exposes an API for managing deployments. In the future, this can be used by the webapp to authenticate requests coming from the kubernetes cluster, too.

A new `Cluster` table is added to the webapp to keep track of which clusters it can make requests to. Each app in the webapp is assigned to run on a specific cluster. Right now, they all run on the same cluster, but this opens the door to one webapp being able to submit sims to multiple clusters. This would be helpful for development so that you can just point your local instance at a running cluster without having to spin one up yourself. It would also be helpful if an app needed to be run on in-house servers.

When a `Cluster` is created in the webapp, it registers itself on the compute cluster:

```python
service_account = Profile.objects.get(user__username="hdoupe")
cluster = Cluster.objects.create(
    service_account="hdoupe",
    url="https://devworkers.compute.studio",
)
cluster.create_user_in_cluster(cs_url="https://dev.compute.studio")
```

On registration, the compute cluster creates a secret that will be used to encode and decode JWT's that encode the username and url of the webapp instance. This secret is returned to the webapp and saved in the Cluster table. The cluster and the webapp both use the new `cs-crypt` package to encrypt the JWT secret before saving it in the database. This `cs-crypt` package is heavily inspired by JupyterHub's [`crypto.py`](https://github.com/jupyterhub/jupyterhub/blob/1.1.0/jupyterhub/crypto.py) module. It uses [`Fernet`](https://cryptography.io/en/latest/fernet/) in the `cryptography` python package to symmetrically encrypt the secret. Both the webapp and cluster are responsible for managing their own cryptography key for use with `Fernet`. This second level of encryption is necessary because each webapp-cluster connection will have its own JWT secret that needs to be stored on the webapp and on the kubernetes side. This ensures that only the encrypted secret is stored in the postgres db on the webapp side and the redis cluster on the kubernetes side.

Once the webapp and cluster have registered with eachother and have stored their own copies of the JWT secret, they can authenticate requests from eachother by using their copy of the JWT secret to encode and decode JWT tokens with information about the user. 

Note that the requests will only be accepted by the kubernetes cluster once the webapp has been "approved". This ensures that random people can't just register with the kubernetes cluster and send requests to it.

A couple things to keep in mind with this setup are:
- Now that traefik is installed in the kubernetes cluster it's easy to add HTTPS which is necessary for encrypting data in transport between the cluster and webapp:
  ```yaml
  apiVersion: traefik.containo.us/v1alpha1
  kind: IngressRoute
  metadata:
    name: scheduler-tls
    namespace: default
  spec:
    entryPoints:
      - websecure
    routes:
    - match: Host(`devworkers.compute.studio`)
      kind: Rule
      services:
        - name: scheduler
          port: 80
    tls:
      certResolver: myresolver
  ```
- Access to the `users-*` keys in the Redis cluster is locked down with the use of ACL added in Redis 6.0. This ensures that not just anyone can connect to the cluster and update information about registered webapps. A todo item is to implement a process for automatically rolling the passwords for the Redis ACL users and perhaps moving the redis deployment to its own kubernetes namespace so that access to it is only allowed to the services that need it.

In addition to looking at Jupyterhub to see how they encrypted cookie signing-secrets, I also checked out:
- [pintrest/snappass](https://github.com/pinterest/snappass): Uses redis as a backend for sharing passwords with teammates and also uses `Fernet` for encrypting the passwords.
- This [conversation](https://hackernoon.com/service-to-service-authentication-for-microservice-apis-ccf4ab8073e6) about securing microservices with practicality/smaller organizations in mind.

**Comment by hdoupe** [comment]
Recent commits:
- Set up billing for visualizations. Currently, things are set up such that:
  - _if_ deployment is associated with an embed --> charge embed owner
  - _else if_ project in deployment has sponsor --> charge sponsor
  - _else_ charge user who started deployment
  Users are charged using the formula: (seconds that the deployment was running) * (cost of resources/second)

  A TODO: is to allow sponsors to set ceilings on how much they are willing to pay for a given month.

- URLs for the link that the viz is running on in the Kubernetes cluster are now random and not obfuscated. The random hash that is added to the deployment name is now generated with [`token_hex`](https://docs.python.org/3/library/secrets.html#secrets.token_hex) from the Python `secrets` module instead of the [hashids libary](https://hashids.org/python/).

**Comment by hdoupe** [comment]
Merging #308. There is still quite a long todo list to go along with adding interactive visualizations. However, merging this will make it easy to start developing UI and administrative features on top of it like:
- Billing limits.
- Streamlined model/sim/viz pages.

Taking the approach of rolling these changes out gradually lets us test them out before doing a big marketing push with the new features.

Further, getting these improvements into master lets us start to apply them to other parts of C/S like using the new deployment monitoring and crud capabilities on the inputs servers for ParamTools-powered apps.

Finally, @peter-metz has already published two viz's on the dev site--so I need to catch up!

**Pull request merged**
