### PR TITLE
Add simulation title and readme

### PR DESCRIPTION
**Pull request by hdoupe**
This allows users to title and write readme's for their simulations using markdown. If a simulation is created from another simulation through the edit page, then the original simulation is saved on the new simulation. This makes it possible to keep track of simulation history. Users will be able to keep their simulations private while they draft their title and readme, and once they are satisfied, they may make it public or choose to keep it private.

**TODO:**
- [x] Clean up UI.
- [x] Notify users when they modify the inputs of an existing simulation page without re-running the simulation.
- [x] Handle server errors on new description component.
- [x] Streamline communication between the frontend and webserver to reduce API payload size and number of API calls.
- [x] Make simulations private until users are ready to make them public.
- [x] Add a model page, focusing on relevant background information for the model and usage instructions. This may be something like an extended version of the existing primary card on simulation pages with a "Create Simulation" button on it.

I'm excited to get feedback on this PR. I think this will make it possible for users to take ownership over their simulations, make the simulations easier to share, and add the necessary context for the complex simulations they create on C/S. I'll add some gifs and deploy the changes on the dev server to better demonstrate what these changes do and make it easier to test out the new features.

Screenshot from 2019-11-21 16-12-03

### CODE REVIEW

**Comment by hdoupe** [comment]
Made some edits to the UI this morning:

Screenshot from 2019-11-22 12-38-27

I'm going to change it so that the edit/save buttons are only displayed to people with write access to the sim.

**Comment by hdoupe** [comment]
Status update:

- Model home page with "create simulation button": 
newsimpt1

- Update title:
newsimpt2

- Outputs page:
newsimpt3

- Create new simulation from existing:
newsimpt4

- View simulation history:
newsimpt5

**Comment by hdoupe** [comment]
The new flow for creating fresh simulations is:

- Go to model home page at `/[owner]/[title]/ `
- Click create simulation button 
- Redirect to `/[owner]/[title]/[model_pk]/edit/` if authenticated and `/[owner]/[title]/[model_pk]/` if not
- Clicking run simulation fills in the outputs for the simulation at `# [model_pk]` or creates a new simulation if the user is not authenticated and has to sign in when clicking run
- Clicking the title box allows you to update the title and it is saved when you click away or press enter (`onBlur`)

The REST API for creating, editing, and viewing `Simulation` and `Inputs` objects now looks like this (owner and title refer to project owner and project title):

`Simulation`:
- Create
  - `POST /[owner]/[title]/api/v1/new/` (TODO)
    - Currently visiting the page `/[owner]/[title]/new/` creates a new simulation for authenticated users and redirects them to it.
  - `POST /[owner]/[title]/api/v1/`
 
- Update
  - `PUT /[owner]/[title]/api/v1/[model_pk]/`
  - `POST /[owner]/[title]/api/v1/[model_pk]/`

- View
  - `GET /[owner]/[title]/api/v1/[model_pk]/`
  - `GET /[owner]/[title]/api/v1/[model_pk]/remote/`

`Inputs`
- Create:
  - only created with the simulation api endpoitns

- Update:
  - `PUT /[owner]/[title]/api/v1/[model_pk]/save/`
  - Simulation endpoints that kick off simulations

- View:
  - `/[owner]/[title]/api/v1/[model_pk]/edit/`
  - TODO: maybe swap `edit` to `inputs` since it is just retrieving the `Inputs` object.

**Comment by hdoupe** [comment]
One of the challenges in this PR has been keeping the `Description`, `InputsForm`, and `Outputs` components synced up. This has made keeping the user's authentication status in sync between the `InputsForm` and `Description` components difficult, but this has also been frustrating when keeping track of whether the form has been modified or not and notifying the user when they click the outptus tab. One way to solve this is to move the `Formik` component up to the top level of the main react app. That way all of the components below have access to the same form state, hopefully, making it easier to keep track of whether the `InputsForm` is in an unsaved state or if the user has signed in through the dialog, as added in PR #195.

**Comment by MattHJensen** [comment]
A few design ideas to consider:

- [ ] Center and accentuate PSLmodels/Tax-Cruncher. Could place a model logo just to its left. This will make it obvious that you are in the Tax-Cruncher room of Compute.Studio
- [ ] Have a dedicated title card that defaults to "Untitled simulation". I think the text size should be modest, like Google docs.
- [ ] Beneath that have a row of tabs or other buttons for Authors, Dependencies, Cite, Modify a Copy
- [ ] We could either include the sim parents as a section under dependencies, or we could add a separate button for it,
- [ ] For the sections that you haven't developed yet, like Cite, we could just leave them off this menu until they're developed.
- [ ] Reduce the amount of dead space in the outputs section, and either take advantage of the real estate by incresing the size of each chart, or packing the charts closer together.
- [ ] add a downward facing arrow to the right of PSLmodels/Tax-Cruncher that offers buttons linking to -Readme and Create Simulation
- [ ] add an alert below the inputs / outputs tab that says something like, "Current results do not reflect un-simulated adjustments. Simulate [link]."
- [ ] Move the preview button to the row of tabs and rename it "Adjustments"

**Comment by hdoupe** [comment]
Thanks for the feedback @MattHJensen! If others want to take a look at this feature, it's live at https://dev.compute.studio

**Comment by hdoupe** [comment]
- [ ] Backwards compatible handling of early, early days outputs.
  - Likely will redirect responses to a url like /PSLmodels/Tax-Brain/v0/model_pk/

**Comment by hdoupe** [comment]
UI is looking much better, and we now have a "Copy Simulation" button:

Screenshot from 2020-01-03 18-21-56

**Comment by hdoupe** [comment]
And the changes are live at https://dev.compute.studio

**Comment by hdoupe** [comment]
Commit https://github.com/compute-tooling/compute-studio/pull/239/commits/4ca5ac1b7f98c7d598ee4197c3d3e9affd0d5cc1 adds a copy simulation API endpoint. This copies the `Simulation` and `Inputs` objects over to a new simulation that is owned by the user who did the copy. Two things about this feature that I haven't completely resolved yet:

- If the inputs are currently validating or if the simulation is still being run, the user cannot copy the simulation. This restriction keeps things simple when the results of the operation are pushed back to the webapp. The inputs are validated pretty quickly, and I doubt that there would be time to copy the simulation while the inputs are pending. I think the only realistic situation where this restriction would be hit is if a user started a simulation and the same user or another copied it while the results are still pending. I don't think it's clear what the obvious outcome should be: should the results from the original sim get copied to the new one when they are done? or should it be treated as a new simulation that needs to be run?

- Initially, the copy was implemented as a rest api endpoint, but it may be more intuitive to add a gui-level endpoint `/[owner]/[title]/[model_pk]/copy/` that is set as the `href` on the "Copy Simulation" button. This would make it easy for the user to right click on the button to open the copied sim in a new tab.

**Comment by hdoupe** [comment]
from @MattHJensen:

- [ ] Able to change the private eye from red to green? Right now it blends in.
- [ ] What do you think about giving people a clear history button at the bottom of the history dropdown?
- [ ] What do you think about writing "This is the Nth simulation in this line" at the top of the history dropdown? In italics or something to slightly stand out from the simulations.
- [ ] What do you think of asking model uploads what they would like to call a run of their model, a "run", a "simulation", "other", and then swap out simulation everywhere for their preference? We would use "runs" as the generic term, such as in a user's dashboard.
- [ ] What do you think about adopting the "fork" terminoligy instead of copy? 
- [ ] Move public/private button to the right of the desktop display? 
- [ ] Can you automatically highlight "untitled simulation" when you click into the box?
- [ ] "Share" button instead of a toggle. We give more information about their sharing status in a popup when they click.

**Comment by hdoupe** [comment]
After incorporating some of @MattHJensen's feedback:

Screenshot from 2020-01-06 13-45-50

Screenshot from 2020-01-06 13-45-15

I also added some icons and fixed the title overflow in the history dropdown. Changes are live at https://dev.compute.studio

**Comment by hdoupe** [comment]
@MattHJensen very nice suggestion on the muted `owner/title #sim number`:

Screenshot from 2020-01-06 14-06-37

**Comment by MattHJensen** [comment]
Looking great! 

Here I prefer "in this line" rather than "in line". 
image

**Comment by MattHJensen** [comment]
>  What do you think of asking model uploads what they would like to call a run of their model, a "run", a "simulation", "other", and then swap out simulation everywhere for their preference? We would use "runs" as the generic term, such as in a user's dashboard.

This one probably doesn't need to be part of this PR. Could be dealt with once we start onboarding more models and witness need directly.

**Comment by hdoupe** [comment]
- [ ] Faster render when user is just trying to view the outputs page (i.e. don't wait on inputs to load before showing the snapshots)

**Comment by hdoupe** [comment]
@MattHJensen asked:
>  What do you think about giving people a clear history button at the bottom of the history dropdown?

This seems like it would be useful if you didn't want to show draft simulations, but it could be irritating if other users' simulations were deleted from the history.

What if we exclude simulations from the history if the simulation viewer doesn't have read access to them? That way the history is preserved but some or all of the previous sims can be hidden from other users.

**Comment by MattHJensen** [comment]
> What if we exclude simulations from the history if the simulation viewer doesn't have read access to them? 

This is elegant, but I'm worried that the simulation creator would need to remember this aspect of C/S behavior and also remember which sims in the history were shared in order to know what the history looks like to others. 

One option would be to split the history dropdown with subheaders into "private history" and "public history". Another option would be to take all unshared sims out of the history for everyone.

**Comment by hdoupe** [comment]
@MattHJensen what if we showed the public/private lock in the dropdown:

Screenshot from 2020-01-07 13-52-02

That way users can quickly see which simulations are public and private. We can add this to the simulation dashboard on the home page too. However, there is some subtlety in this approach that people might miss that seems obvious to me: private simulations are only visible to users with admin access.

On the other hand, showing a public and private history to users with admin access to the simulation is an explicit way to show what's going on. Downside is that it makes the dropdown a little more busy. I'll implement this and post a screenshot.

**Comment by hdoupe** [comment]
Here's how the split history's would look:
Screenshot from 2020-01-07 14-27-36
Screenshot from 2020-01-07 14-30-21

**Comment by hdoupe** [comment]
Mmmm, I've come around to the split histories. This looks nice (and you can see that I'm having fun with the titles):
Screenshot from 2020-01-07 14-43-29

**Comment by hdoupe** [comment]
- [ ] (time permitting) soften up tooltips

**Comment by hdoupe** [comment]
Commit https://github.com/compute-tooling/compute-studio/pull/239/commits/dd4ec89c1cfc36c573663adee00c49942426f589 adds layer for handling v0 outputs:
- Redirect to /[owner]/[title]/[model_pk]/v0/
- UI for v0 outputs for edit page that shows a big, green
  button for getting to the right outputs page.
- Annotation, history, etc. still works for v0 outputs.

Users can still view the simulation on the new Simulation page if they go to the edit url. In this case, the outputs page looks like this:
Screenshot from 2020-01-10 13-10-28

**Comment by hdoupe** [comment]
Latest commits add an editor using Slate:

Screenshot from 2020-01-13 11-43-59

**Comment by hdoupe** [comment]
Latest commits add placeholders for the description box. If the user has write access to the simulation and the description is empty the placeholder is "You may use this space to describe your simulation." and if the user does not have write access: "No description provided for this simulation."

Screenshot from 2020-01-13 13-33-09
Screenshot from 2020-01-13 13-32-14

**Comment by hdoupe** [comment]
- [ ] Use something like [React Portals](https://reactjs.org/docs/portals.html) to hook into the "Sign in" and "Sign up" buttons (time permitting). This would help smooth out the description box sign in and edit flow.

**Comment by hdoupe** [comment]
Latest commits use React Portal to replace the django templated Profile/Sign in and Sign up buttons with React Components. This makes it possible for users to sign in or sign up from simulation page. I still need to tweak the UI on the buttons since some of the formatting was lost in the translation to React.

@MattHJensen when you get a sec, can you take a look at them and let me know how they work for you?

**Comment by hdoupe** [comment]
Actually this needs a little more work on the "new" page.

**Comment by hdoupe** [comment]
Commit https://github.com/compute-tooling/compute-studio/pull/239/commits/8ea839031be7d09f4b5d8e13115ff0537ed6fbca makes it possible for all simulations created before this PR's deploy date to remain anonymous. This preserves the public nature of the simulations created on Compute Studio so far while preserving the identities of their creators. 

The `get_owner` method on the `Simulation` model checks whether the simulation was created before `ANON_BEFORE` (which will be set to the deploy date) and returns the username of the owner of the simulation if the creation date is after the cut off and "anonymous" if the creation date is before the cutoff date. The data serializers for `Simulation` exclusively use `get_owner` to retrieve the owner of the simulation for the API response, making it easy to set the privacy constraint in one place in the code base and keeping the identity of the owners of existing simulations private in the GUI as well as the REST API.

This change is live on https://dev.compute.studio, and the cut off date is set to 12/31/2019 for testing purposes. To demonstrate how this works you can check a simulation created before this date:

1. Anonymous in the GUI:

Screenshot from 2020-01-14 13-11-37

2. Anonymous in the REST API:

Screenshot from 2020-01-14 13-13-31

Screenshot from 2020-01-14 13-14-11

Then, check simulations after this date:

1. Owner in the GUI:
Screenshot from 2020-01-14 13-18-20


2. Owner in the REST API, but not in the parent simulations created before `ANON_DATE`:
Screenshot from 2020-01-14 13-19-13
Screenshot from 2020-01-14 13-19-37

**Comment by hdoupe** [comment]
The latest commits streamline the authentication flow for the simulation page.

When users sign in or sign up from the /new/ page, a simulation is created and they are able to edit the title, description, and submit it immediately.
new-sim-with-auth

Users can sign in to existing simulations and edit, fork, or "fork and run" them:
more-auth-sims

**Pull request merged**
