### PR TITLE
Revamp simulations tab

### PR DESCRIPTION
**Pull request by hdoupe**
This PR improves the design for the simulations view for the home and profile pages. It also swaps from the page from django templating to React. This makes it easy to dynamically load the simulations, add pagination and sorting, and make it possible to edit simulation data like its title and public/private status. The dynamic loading + pagination makes the home page load almost instantly and vastly improves on the long delays that are experienced on the current home page.

Screenshot from 2020-02-06 13-51-12
 
TODO:
- [x] Keep iterating on simulation design
- [x] Wire up simulation editing with the backend
- [x] Add tests for new api endpoints.
  - This shouldn't be bad because DRF does the heavy lifting for us here.

### CODE REVIEW

**Comment by hdoupe** [comment]
Latest commits clean up the sim design:

Screenshot from 2020-02-06 16-56-56

**Comment by hdoupe** [comment]
This PR has evolved into a re-design on the home page. Here's how my home page looks:


Screenshot from 2020-02-12 15-19-14
Screenshot from 2020-02-12 15-19-29

And my **public** profile page looks like this:

Screenshot from 2020-02-12 15-20-34
Screenshot from 2020-02-12 15-20-47

Users can also update the visibility status and title for their simulations. The version is also retrieved dynamically from the workers so publishers can easily check which version of their models is running on C/S.

**Comment by hdoupe** [comment]
@MattHJensen how's this look? Ready to ship it?

**Comment by MattHJensen** [comment]
Looks great!

**Pull request merged**
